<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>
<body>
    <script>
        // resolve, reject, all, ract
        let promise = new Promise((resolve, reject) => {
            resolve(11111);
        });

        // promise.then(response => {
        //     console.log('成功');
        //     console.log(response);
        // }).catch(error => {
        //     console.log('失败');
        // });

        // 链式
        function promise1(status){
            return new Promise((resolve, reject) => {
                if(status){
                    console.log('第1个Promise成功');
                    resolve('第1个Promise返回数据成功');
                }else{
                    console.log('第1个Promise失败');
                    reject('第1个Promise返回数据失败');
                }
            })
        }

        function promise2(status){
            return new Promise((resolve, reject) => {
                if(status){
                    console.log('第2个Promise成功');
                    resolve('第2个Promise返回数据成功');
                }else{
                    console.log('第2个Promise失败');
                    reject('第2个Promise返回数据失败');
                }
            })
        }

        function promise3(status){
            return new Promise((resolve, reject) => {
                if(status){
                    console.log('第3个Promise成功');
                    resolve('第3个Promise返回数据成功');
                }else{
                    console.log('第3个Promise失败');
                    reject('第3个Promise返回数据失败');
                }
            })
        }

        // promise1(false).then(response => {
        //     console.log(response);
        //     return promise2(true);
        // }).then(response => {
        //     console.log(response);
        //     return promise3(true);
        // }).then(response => {
        //     console.log(response);
        // }).catch(error => {
        //     console.log(error);
        // });

        // all 数组内所有个Promise全部执行成功才会回调，只有有一个不成功就会执行catch
        // Promise.all([promise1(true), promise2(true), promise3(true)]).then(response => {
        //     console.log('全部调用成功');
        // }).catch(error => {
        //     console.log('有些调用失败');
        // })

        // race数组，当执行时，遇到的结果为resolve（成功），一直执行链式，第一个为false就返回失败
        Promise.race([promise1(false), promise2(false)], promise3(true)).then(response => {
            console.log('调用成功');
        }).catch(error => {
            console.log('有些调用失败');
        })

    </script>
</body>
</html>